### PR TITLE
prevent “_FORTIFY_SOURCE” redefinition

### PR DESCRIPTION
**Pull request by mpkh**

### CODE REVIEW

**Comment by mpkh** [comment]
Wowzers, this Travis is hella mad, may somebody tell me what's going there with CONFIGRATION 0 1 2 3 and clang?

**Comment by saschazelzer** [comment]
Well, the system tests the code base with gcc and clang, using different CMake build configurationns.

Anyways, I would merge your branch to the development branch (we do not merge directly to `master`). If you want, you can send another PR for `development` and see how Travis behaves there. If all is good, I could merge that PR directly.

**Comment by mpkh** [comment]
@saschazelzer I see, should I re-open this to develop?

**Comment by saschazelzer** [comment]
Yes please.

**Comment by mpkh** [comment]
@saschazelzer yep, here https://github.com/CppMicroServices/CppMicroServices/pull/120

**Pull request closed without merging**
