### PR TITLE
Test CI with OS X

### PR DESCRIPTION
**Pull request by karthikreddy09**
Add Mac OS X to travis CI builds

### CODE REVIEW

**Comment by saschazelzer** [comment]
Awesome, having Mac OS supported by Travis CI will be great.

A few comments:
 * If you want to test CI config changes, just pushing the branch itself is enough and will trigger the CI hooks. You don't need a PR.
 * Some elements in the build matrix have `addons: &valgrind` and some don't. What is the purpose of the `&` ?
 * It is unfortunate that we need to expand the build matrix manually. When we re-enable the single-threaded build configuration, this will double the number of entries. But given my understanding of the Travis CI config file and the need for the `MACOSX_DEPLOYMENT_TARGET` environment variable, I couldn't think of a cleaner way :-/

Thanks for working on this!

**Comment by saschazelzer** [comment]
Oh, and the Linux Clang configurations are not supported on Ubuntu Trusty. Clang just doesn't play well with `libstdc++` from gcc with C++11 enabled, so I suggest to just remove these entries from the build matrix.

**Comment by karthikreddy09** [comment]
I noticed the push/branch CI nodes but never made the connection. 

(&) is used to create anchor nodes in YAML. The same nodes can be later referenced using a (*). The anchor and reference nodes can be used to remove redundancy in the file. I haven't yet figured how to do it right in our yml file

**Comment by karthikreddy09** [comment]
@CppMicroServices/developers let me know if you are OK with merging this PR.

**Comment by saschazelzer** [comment]
+1 for merging

This is really nice to have!

**Pull request merged**
