### PR TITLE
fix building on FreeBSD (dl is linux only, bsd has it with libc)

### PR DESCRIPTION
**Pull request by mpkh**
seems like not relevant for development branch

### CODE REVIEW

**Comment by saschazelzer** [comment]
Thanks for the pull request. Normally, we only accept PRs targeting the development branch, see our [contribution guidelines](https://github.com/CppMicroServices/CppMicroServices/blob/development/CONTRIBUTING.md) for the details.

The issues still is relevant for the development branch. Instead of relying on `CMAKE_SYSTEM_NAME`, I suggest to use a `find_library` call for `dl` and link to it only if the resulting variable is valid.

**Comment by mpkh** [comment]
Strange but on development branch I can't see manual `dl` linking there
https://github.com/CppMicroServices/CppMicroServices/blob/development/CMakeLists.txt

**Comment by saschazelzer** [comment]
Yes, the project structure changed. Now it is here: https://github.com/CppMicroServices/CppMicroServices/blob/development/framework/CMakeLists.txt#L23

**Comment by mpkh** [comment]
@saschazelzer okay I'll try to elaborate it

**Pull request closed without merging**
