### PR TITLE
701 include-fixes and spdlog/jsoncpp update for clang-14 builds based on gcc11's libstdc++

### PR DESCRIPTION
**Pull request by insi-eb**
This PR is a preparation for further contribution on the c++14 branch and a first test of the contribution process for me.

GCC-11 has restructured the headers of its standard library to reduce the transitive inclusion of unneeded headers. Building on a device with that standard library as default requires more explicit header include statements.

Also updated spdlog to the latest 1.x release (1.10 as of now) to get a warning-free build with clang-14 and jsoncpp to latest 1.x release (1.9.5 as of now) to get a warning-free build with gcc 7.5

### CODE REVIEW

**Review by achristoforides — CHANGES_REQUESTED** [review]
Hi @insi-eb , thanks for your PR!

I realized that building CppMicroServices on GCC11 didn't work as a result of a change to include files but I didn't realize that this also affected Clang 14. I submitted a [change](https://github.com/CppMicroServices/CppMicroServices/commit/fa69c781d037997f0ac70bf7e3560476220994d8) the other day to `development` to address this; thank you for providing this change to the `c++14-compliant` branch 😄

~~The only flag I have regarding this PR is whether updating json-cpp will negatively affect performance regarding how json is parsed/read in the core framework and the resource compiler.~~

~~Could you please provide benchmark results for the benchmark tests in development versus results from the benchmark tests in your branch (insi-eb:701-clang-14_gcc11_build)? Simply providing the "*_mean" results for the tests in framework/test/benchmark should be sufficient as I just want to be sure that upgrading the third-party library doesn't result in any regressions.~~

~~Assuming no regressions (which would be my expectation), we can merge this into the c++14-compliant branch and merge it forward to development as well.~~

**Comment by achristoforides** [comment]
Additionally, can you please integrate [these changes](https://github.com/CppMicroServices/CppMicroServices/pull/723) into your PR so that the GitHub Actions CI jobs run on this PR and on the `c++14-compliant` branch?

**Review by achristoforides — APPROVED** [review]
Upon second review, `json-cpp` is not used in the core framework. You can ignore my previous comment.

Please still integrate the changes linked in my prior comment so that the CI jobs are ran.

**Comment by insi-eb** [comment]
I merged the workflow changes manually as one file-name was different

**Comment by insi-eb** [comment]
I'll look at the failures - at a first glance, compiler warnings for some compiler versions I haven't built with

**Comment by insi-eb** [comment]
I fixed the compiler warnings in jsoncpp and squashed the fixes into the jsoncpp update commit

Should/can I do anything about the reduced coverage? Should 3rdparty code be even part of the coverage measurement?

**Comment by jeffdiclemente** [comment]
> I fixed the compiler warnings in jsoncpp and squashed the fixes into the jsoncpp update commit
> 
> Should/can I do anything about the reduced coverage (is that caused by failed tests?)?

Nothing needs to be done about the reduced coverage. This doesn't look like it was caused by failed tests. codecov is diffing this PR against d955a42, which I guess produces a 0.09% decrease. No changes to shipping, non-third party code were made so I'm not concerned.

**Pull request merged**
