### PR TITLE
Complete implementation of HTTPService

### PR DESCRIPTION
**Pull request by arcadien**
* Enhance implementation of GET and POST method in HttpService
* Implement management of file upload using POST/multipart, following the Servlet(c) API
* Allow to provide options to CivetWeb when starting a ServletContainer
* Allow to run GTest in a HttpService-enabled environment
* Implement unit/functional tests for HttpService

### CODE REVIEW

**Comment by arcadien** [comment]
@saschazelzer it look we are not using the same clang-format version, since our 'format-source.sh' run has produced difference in source format. We are using clang-format 6.0.0.

**Comment by saschazelzer** [comment]
@arcadien This is strange, I am also using clang-format 6.0.0. Anyway, I don't care too much. You could just format the files you touched (or not format them at all) and we are going to re-format everything from time to time. This should not be a major source of pain. If you want help with the CI test errors, you could share what your current status is and we could try and help out.

BTW, many thanks for working on this, it is much appreciated.

**Comment by arcadien** [comment]
@saschazelzer we will remove untouched files where syntax has been broken to have a more consistent pull request. Also, we will improve the test coverage on some HttpService components so that the total coverage does not decrease.
We may need some help in debugging errors with Clang builds we don't really understand (and we haven't Clang in our own buildchain).

**Comment by arcadien** [comment]
I will do my best for coverage enhancement here and keep the branch sync with your development tree.
It is quite hard to find time since _it works for us_ as is.

**Comment by arcadien** [comment]
Hello @saschazelzer , long time no activity there. If interest is still here I can upgrade the pull request.
* Bump Civet to 1.15 (had to to it for Visual Studio pro 2022 compilation)
* Code move from test utils to first class framework utils (temp file and folder creation)
* Upgrade of HTTPService itself

Let me know!

**Comment by arcadien** [comment]
referring to old discussion, i also switched on clang-format 15.0.6

**Comment by jeffdiclemente** [comment]
> Hello @saschazelzer , long time no activity there. If interest is still here I can upgrade the pull request.
> 
> * Bump Civet to 1.15 (had to to it for Visual Studio pro 2022 compilation)
> * Code move from test utils to first class framework utils (temp file and folder creation)
> * Upgrade of HTTPService itself
> 
> Let me know!

Hi @arcadien , we would be happy to review any changes you have for this PR!

**Comment by jeffdiclemente** [comment]
closing as there have been no code updates in years.

**Pull request closed without merging**
