### PR TITLE
Add MSVC analysis to project

### PR DESCRIPTION
**Pull request by achristoforides**
Signed-off-by: The MathWorks, Inc. <alchrist@mathworks.com>

### CODE REVIEW

**Review by pelliott-mathworks — COMMENTED** [review]
Looks good!

**Review by carneyweb — COMMENTED** [review]
Ship it!

**Review by jeffdiclemente — COMMENTED** [review]
could you provide a link to more information on MSVC Code Analysis?

**Comment by achristoforides** [comment]
> could you provide a link to more information on MSVC Code Analysis?

https://github.com/microsoft/msvc-code-analysis-action

**Pull request merged**
